# Generated by Django 3.1.1 on 2020-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANPR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
