# Generated by Django 3.1.1 on 2020-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANPR', '0002_user_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='payment',
            new_name='paymentDone',
        ),
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
